<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        @page { margin: 26px 30px; }
        body { font-family: Helvetica, Arial, sans-serif; font-size: 10.5px; color: #16211D; }
        h1 { font-size: 17px; margin: 0 0 2px; color: #0A3F37; text-align: center; }
        .subtitle { font-size: 11px; color: #5B6B65; margin-bottom: 4px; text-align: center; }
        .divider { border-top: 2px solid #0F5C50; margin: 10px 0 14px; }
        table.infotable { width: 100%; border-collapse: collapse; margin-bottom: 14px; }
        table.infotable td { padding: 3px 6px; font-size: 10px; vertical-align: top; }
        table.infotable td.label { color: #5B6B65; width: 100px; }
        table.data { width: 100%; border-collapse: collapse; }
        table.data th { background: #0F5C50; color: #ffffff; text-align: left; padding: 6px 8px; font-size: 9px; text-transform: uppercase; letter-spacing: 0.03em; }
        table.data td { padding: 5px 8px; border-bottom: 1px solid #DCE3DF; font-size: 9.5px; }
        table.data tr:nth-child(even) td { background: #F2F4F2; }
        .num { text-align: right; font-family: 'DejaVu Sans Mono', monospace; }
        .total-row td { border-top: 2px solid #0F5C50; font-weight: bold; background: #E4EFEC; }
        .voided td { color: #A6402C; text-decoration: line-through; }
        .summary { margin-top: 16px; padding: 10px 14px; background: #E4EFEC; border-radius: 4px; font-size: 11px; font-weight: bold; color: #0A3F37; }
        .footer { margin-top: 20px; font-size: 8px; color: #8FB3A9; text-align: center; }
        .empty { text-align: center; padding: 30px 10px; color: #5B6B65; font-size: 12px; }
    </style>
</head>
<body>
    @include('reports.pdf.partials.company-header')
    <div class="divider"></div>

    <h1>Reimbursement Report</h1>
    <div class="subtitle">
        Coverage Period: {{ $benefitPeriod->from_date->format('M d, Y') }} &ndash; {{ $benefitPeriod->to_date->format('M d, Y') }}
    </div>

    <table class="infotable">
        <tr>
            <td class="label">Member code</td><td>{{ $member->code }}</td>
            <td class="label">Member name</td><td>{{ $member->full_name }}</td>
        </tr>
        <tr>
            <td class="label">Date generated</td><td>{{ $generatedAt->format('M d, Y g:i A') }}</td>
            <td class="label">Generated by</td><td>{{ $generatedBy->name ?? '—' }}</td>
        </tr>
    </table>

    @if ($reimbursements->isEmpty())
        <div class="empty">
            No reimbursement records found for:<br>
            {{ $benefitPeriod->from_date->format('M d, Y') }} &ndash; {{ $benefitPeriod->to_date->format('M d, Y') }}
        </div>
    @else
        <table class="data">
            <thead>
                <tr>
                    <th>Member name</th>
                    <th>Reimbursement period</th>
                    <th>OR date</th>
                    <th>OR no.</th>
                    <th>Hospital</th>
                    <th class="num">Amount</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($reimbursements as $reimbursement)
                    <tr class="{{ $reimbursement->is_voided ? 'voided' : '' }}">
                        <td>{{ $member->full_name }}</td>
                        <td>{{ $reimbursement->or_date->format('F Y') }}</td>
                        <td>{{ $reimbursement->or_date->format('M d, Y') }}</td>
                        <td>{{ $reimbursement->or_no ?: '—' }}</td>
                        <td>{{ $reimbursement->hospital_name ?: '—' }}</td>
                        <td class="num">&#8369;{{ number_format($reimbursement->or_amount, 2) }}</td>
                        <td>{{ $reimbursement->is_voided ? 'Voided' : 'Approved' }}</td>
                    </tr>
                @endforeach
                <tr class="total-row">
                    <td colspan="5">Total{{ $voidedCount ? ' ('.$voidedCount.' voided, excluded)' : '' }}</td>
                    <td class="num">₱{{ number_format($total, 2) }}</td>
                    <td></td>
                </tr>
            </tbody>
        </table>

        <div class="summary">
            Total Reimbursement Records: {{ $reimbursements->count() }}<br>
            Total Reimbursement Amount: ₱{{ number_format($total, 2) }}
        </div>
    @endif

    <div class="footer">Group Hospitalization Plan &mdash; Reimbursement Report. Generated {{ $generatedAt->format('Y-m-d H:i') }}.</div>
</body>
</html>
